In [5]:
from tensorflow.keras.preprocessing.text import Tokenizer, text_to_word_sequence
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding
from tensorflow.keras.utils import to_categorical
from numpy import array

In [6]:
text = '해보지 않으면 해낼 수 없다.'

In [9]:
result = text_to_word_sequence(text) # 토크나이징을 자동으로 해준다.
print("원문: ", text)
print("토큰화: ", result) # 토큰, 코퍼스(corpus)

원문:  해보지 않으면 해낼 수 없다.
토큰화:  ['해보지', '않으면', '해낼', '수', '없다']


# 토크나이저 사용법

In [11]:
#단어 빈도수 세기
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화 합니다.',
       '텍스트의 단어로 토큰화해야 딥러닝에서 인식됩니다.',
       '토큰화한 결과는 딥러닝에서 사용할 수 있습니다.']


In [12]:
# 문장 토큰화 하기
token =Tokenizer(lower=False)
token.fit_on_texts(docs)

In [13]:
print('단어 카운트: ', token.word_counts)

단어 카운트:  OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화', 1), ('합니다', 1), ('단어로', 1), ('토큰화해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('토큰화한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])


In [15]:
print('문장 카운트:', token.document_count)

문장 카운트: 3


In [16]:
print('각 단어가 몇 개의 문장에 포함되어 있는가?', token.word_docs)

각 단어가 몇 개의 문장에 포함되어 있는가? defaultdict(<class 'int'>, {'토큰화': 1, '합니다': 1, '단어를': 1, '텍스트의': 2, '나누어': 1, '각': 1, '먼저': 1, '토큰화해야': 1, '인식됩니다': 1, '단어로': 1, '딥러닝에서': 2, '사용할': 1, '수': 1, '토큰화한': 1, '결과는': 1, '있습니다': 1})


텍스트의 2는 2개의 문장에 포함되어있다,.

In [17]:
print('각 단어에 매겨진 인덱스:', token.word_index)

각 단어에 매겨진 인덱스: {'텍스트의': 1, '딥러닝에서': 2, '먼저': 3, '각': 4, '단어를': 5, '나누어': 6, '토큰화': 7, '합니다': 8, '단어로': 9, '토큰화해야': 10, '인식됩니다': 11, '토큰화한': 12, '결과는': 13, '사용할': 14, '수': 15, '있습니다': 16}


# 단어의 원-핫 인코딩

In [18]:
text = '오랫동안 꿈꾸는 이는 그 꿈을 닮아간다.'
token = Tokenizer(lower=False)
token.fit_on_texts([text])
print(token.word_index)

{'오랫동안': 1, '꿈꾸는': 2, '이는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}


In [20]:
# 단어를 벡터로 변환
x = token.texts_to_sequences([text])

In [24]:
# 인덱스에 1을 추가해서 원-핫 인코딩 배열 만들기, 
word_size = len(token.word_index) + 1 

In [22]:
word_size

6

In [25]:
x = to_categorical(x, num_classes=word_size) # 배열이 정상적으로 들어가려면 +1을 해줘야 한다. 그래서 앞을 0으로 만들어줘야 해
print(x)

[[[0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 1.]]]


# 텍스트를 읽고 긍정, 부정 예측하기

In [51]:
docs = ["너무 재미있네요",
       "한 번 더 보고싶네요",
       "최고에요",
       "참 잘 만든 영화이네요.",
       "추천하고싶은 영화입니다.",
        "조금 아쉬워요",
       "이건 별로에요",
       "그냥 그래요",
       "생각보다 지루해요",
       "최악이에요"]

#긍정 리뷰는 1, 부정리뷰는 0으로 클래스 지정
classes = array([1,1,1,1,1,0,0,0,0,0])

In [52]:
# 토큰화
token = Tokenizer(lower=False)
token.fit_on_texts(docs)
print(token.word_index)

{'너무': 1, '재미있네요': 2, '한': 3, '번': 4, '더': 5, '보고싶네요': 6, '최고에요': 7, '참': 8, '잘': 9, '만든': 10, '영화이네요': 11, '추천하고싶은': 12, '영화입니다': 13, '조금': 14, '아쉬워요': 15, '이건': 16, '별로에요': 17, '그냥': 18, '그래요': 19, '생각보다': 20, '지루해요': 21, '최악이에요': 22}


In [53]:
#원핫인코딩
x = token.texts_to_sequences(docs)
print(x)

[[1, 2], [3, 4, 5, 6], [7], [8, 9, 10, 11], [12, 13], [14, 15], [16, 17], [18, 19], [20, 21], [22]]


In [34]:
# 패딩 추가, 단어가 제일 긴 []에 맞춤.
# 길이 먼저 찾기 숙제!!!
for i in x:
    print(len(i))

2
4
1
4
2
2
2
2
2
2
1
4


In [54]:
# 패딩 추가, pad_sequences(데이터, 가장 긴 문장의 길이)
padded_x = pad_sequences(x, 4)
print("패딩 결과", padded_x)

패딩 결과 [[ 0  0  1  2]
 [ 3  4  5  6]
 [ 0  0  0  7]
 [ 8  9 10 11]
 [ 0  0 12 13]
 [ 0  0 14 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0 20 21]
 [ 0  0  0 22]]


In [55]:
# 임베딩에 입력된 단어의 수 지정
word_size = len(token.word_index) + 1

In [58]:
# 임베딩에 입력된 단어의 수 지정
word_size

23

In [56]:
# 단어 임베딩을 포함해서 딥러닝 모델 생성
model = Sequential()
model.add(Embedding(word_size, 8, input_length=4))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 4, 8)              184       
                                                                 
 flatten_2 (Flatten)         (None, 32)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 217
Trainable params: 217
Non-trainable params: 0
_________________________________________________________________


In [57]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
history = model.fit(padded_x, classes, epochs=20)
print('Accuracy: ',model.evaluate(padded_x, classes)[1])

Epoch 1/20
1/1 [==============================] - 4s 4s/step - loss: 0.6857 - accuracy: 0.8000
Epoch 2/20
1/1 [==============================] - 0s 37ms/step - loss: 0.6835 - accuracy: 0.9000
Epoch 3/20
1/1 [==============================] - 0s 50ms/step - loss: 0.6813 - accuracy: 0.9000
Epoch 4/20
1/1 [==============================] - 0s 33ms/step - loss: 0.6790 - accuracy: 0.9000
Epoch 5/20
1/1 [==============================] - 0s 81ms/step - loss: 0.6768 - accuracy: 0.9000
Epoch 6/20
1/1 [==============================] - 0s 67ms/step - loss: 0.6746 - accuracy: 0.9000
Epoch 7/20
1/1 [==============================] - 0s 67ms/step - loss: 0.6724 - accuracy: 0.9000
Epoch 8/20
1/1 [==============================] - 0s 18ms/step - loss: 0.6701 - accuracy: 0.9000
Epoch 9/20
1/1 [==============================] - 0s 0s/step - loss: 0.6679 - accuracy: 0.9000
Epoch 10/20
1/1 [==============================] - 0s 4ms/step - loss: 0.6656 - accuracy: 1.0000
Epoch 11/20
1/1 [=================